version: "3.7"

services:
  gui:
    image: guilocal
    build: .
    volumes:
      - ./vnc:/home/user/.vnc
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./caddy:/home/user/caddy
    ports:
      - 5901:5901
      - 5900:5900
      - 11801:11801
      - 80:80
      - 443:443
        #    environment:
        #      - WEBSOCKIFY_PORT=9999
